language: rust
rust:
  - nightly
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt-nightly
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --release --target wasm32-unknown-unknown --all-targets
  - cargo test
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
