language: rust
rust:
  - nightly
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add wasm32-unknown-unknown
  - (which rustfmt && cargo fmt --version) || cargo install rustfmt-nightly --force
  - which cargo-web || cargo install cargo-web
script:
  - cargo fmt -- --write-mode=diff
  - cargo web build --target-webasm --bin websocket_api_web
  - cargo build --no-default-features --features "create_project"
  - cargo test
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
